name: cherry_mvp
description: Cherry MVP
version: 0.0.1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.6.4
  cloud_functions: ^5.3.3
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.2
  go_router: ^14.8.0
  provider: ^6.1.2
  fluttertoast: ^8.2.1
  logging: ^1.3.0
  image_picker: ^0.8.4+4
  flutter_dotenv: ^5.0.2
  google_sign_in: ^6.2.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the assets and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic