// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMgSlx4VI9Fizft4LzWSohYt09k_UtCdM',
    appId: '1:401854471349:web:9b9538f1c44b2d1e85f2fc',
    messagingSenderId: '401854471349',
    projectId: 'cherry-mvp',
    authDomain: 'cherry-mvp.firebaseapp.com',
    storageBucket: 'cherry-mvp.firebasestorage.app',
    measurementId: 'G-RWZMTRVS51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKF0hkCPR2nhUfv_CsgZFsnWcx7hjkep4',
    appId: '1:401854471349:android:cad8afc621be102485f2fc',
    messagingSenderId: '401854471349',
    projectId: 'cherry-mvp',
    storageBucket: 'cherry-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jkZAhIsFB-7pmtJT-x3kw7ZLBUxOuHQ',
    appId: '1:401854471349:ios:d18d58e54120645085f2fc',
    messagingSenderId: '401854471349',
    projectId: 'cherry-mvp',
    storageBucket: 'cherry-mvp.firebasestorage.app',
    iosBundleId: 'com.cherry.cherrymvp',
  );
}
